# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_siva',
                'doc_host': 'https://SIVARANGA.github.io',
                'git_url': 'https://github.com/SIVARANGA/nbdev_siva',
                'lib_path': 'nbdev_siva'},
  'syms': { 'nbdev_siva.core': { 'nbdev_siva.core.Card': ('core.html#card', 'nbdev_siva/core.py'),
                                 'nbdev_siva.core.Card.__init__': ('core.html#card.__init__', 'nbdev_siva/core.py'),
                                 'nbdev_siva.core.Card.__str__': ('core.html#card.__str__', 'nbdev_siva/core.py'),
                                 'nbdev_siva.core.foo': ('core.html#foo', 'nbdev_siva/core.py')}}}
