# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'Card']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 10
class Card:
    "A playing card created by passing in rank and suit as below"
    def __init__(self,
                 suit:int, # An index into 'suite'
                 rank:int): # An index into 'ranks'
        self.suit,self.rank=suit,rank
    def __str__(self): return f'{ranks[self.rank]}{suits[self.suit]}'
    __repr__=__str__
